const screenWidth = 600;
const screenHeight = 400;

const initialState = Object.freeze({
  _update: 0,
  background: {
    image: backgroundImage,
    y: 0,
    x: 0,
    speed: { x: 0, y: 0 },
    direction: { x: 0, y: 1 },
    width: 600,
    height: screenHeight,
  },
  seabottom: {
    image: seaBottomImage,
    y: 0,
    x: 0,
    speed: { x: 0, y: 0.05 },
    direction: { x: 0, y: 1 },
    width: screenWidth,
    height: screenHeight,
  },
  cliff1_0: {
    image: cliff1Image,
    y: 0,
    x: 0,
    speed: { x: 0, y: 0.3 },
    direction: { x: 0, y: 1 },
    width: screenWidth,
    height: screenHeight,
  },
  cliff1_1: {
    image: cliff1Image,
    y: -screenHeight,
    x: 0,
    speed: { x: 0, y: 0.3 },
    direction: { x: 0, y: 1 },
    width: screenWidth,
    height: screenHeight,
  },
  cliff2_0: {
    image: cliff2Image,
    y: 0,
    x: 0,
    speed: { x: 0, y: 0.7 },
    direction: { x: 0, y: 1 },
    width: screenWidth,
    height: screenHeight,
  },
  cliff2_1: {
    image: cliff2Image,
    y: -screenHeight,
    x: 0,
    speed: { x: 0, y: 0.7 },
    direction: { x: 0, y: 1 },
    width: screenWidth,
    height: screenHeight,
  },
  seaweed: {
    image: seaweedImage,
    y: 0,
    x: 0,
    speed: { x: 0, y: 1.5 },
    direction: { x: 0, y: 1 },
    width: screenWidth,
    height: screenHeight,
  },
  player: {
    image: playerImage,
    speed: { x: 2, y: 10 },
    direction: { x: 1, y: 1 },
    x: (screenWidth - 20) / 2,
    y: 0, //screenHeight - 20,
    width: 20,
    height: 20,
    jumping: false,
    allowJump: true,
  },

  bubbles: [
    {
      x: (screenWidth - 20) / 5 - screenWidth / 5 / 2,
      y: screenHeight,
      speed: { x: 0, y: 2 },
      direction: { x: 0, y: -1 },
      image: bubbleImage,
      burstLevel: 100,
      width: 20,
      height: 20,
    },
    {
      x: (screenWidth - 20) / (5 / 2) - screenWidth / 5 / 2,
      y: screenHeight,
      speed: { x: 0, y: 2 },
      direction: { x: 0, y: -1 },
      image: bubbleImage,
      burstLevel: 100,
      width: 20,
      height: 20,
    },
    {
      x: (screenWidth - 20) / (5 / 3) - screenWidth / 5 / 2,
      y: screenHeight,
      speed: { x: 0, y: 2 },
      direction: { x: 0, y: -1 },
      image: bubbleImage,
      burstLevel: 100,
      width: 20,
      height: 20,
    },
    {
      x: (screenWidth - 20) / (5 / 4) - screenWidth / 5 / 2,
      y: screenHeight,
      speed: { x: 0, y: 2 },
      direction: { x: 0, y: -1 },
      image: bubbleImage,
      burstLevel: 100,
      width: 20,
      height: 20,
    },
    {
      x: screenWidth - 20 - screenWidth / 5 / 2,
      y: screenHeight,
      speed: { x: 0, y: 2 },
      direction: { x: 0, y: -1 },
      image: bubbleImage,
      burstLevel: 100,
      width: 20,
      height: 20,
    },
  ],

  eternalVoid: false,
  animateBackground: false,
  gravity: 0.2,
});
